### ISSUE TITLE
复现没成功

### ISSUE THREAD

**Issue by Hus3ar** [AbelChe/evil_minio#2]
复现成功

**Comment by u1s1jth** [comment]
大佬怎么复现的，方便分享一下吗

**Comment by Hus3ar** [comment]
@AbelChe 大佬应该写的更详细一些。
@u1s1jth 图片里面的意思应该是先去minio官网在自己VPS上源码搭建了一台更新服务器，然后minio mc来更新，成功了。然后再用作者自己该了恶意payload的包重新搭建，这样防止替换二进制程序minio挂了。

**Comment by Hus3ar** [comment]
然后替换的二进制程序运行后，?alive=whoami就可以命令执行了

**Comment by savior-only** [comment]
@Hus3ar 大佬，方便联系一下吗，一直复现失败
